### ISSUE TITLE
File names

### ISSUE THREAD

**Issue by akudrya** [AstroDigital/modis-ingestor#11]
@drewbo thanks a lot for the presentation.

The product looks amazing.

2 minor issues I'd mention with file names:
1. `_` char may cause some problems. e.g. rasterio by default doesn't accept it in file names.
2. There is a little bit of confusion between the folder structure and the list of bands on [USGS]( https://lpdaac.usgs.gov/dataset_discovery/modis). Is B00 the QA band? Are other band numbers match to file names?

**Comment by matthewhanson** [comment]
@akudrya Right now those are band indexes, they should all be increased by one, am pushing a change shortly.

**Comment by drewbo** [comment]
Also @akudrya the bands correspond to the specific product type here: https://lpdaac.usgs.gov/dataset_discovery/modis/modis_products_table/mcd43a4_v006

**Comment by akudrya** [comment]
@drewbo 

>_ char may cause some problems. e.g. rasterio by default doesn't accept it in file names.

Wasn't reproduced. Rasterio accepts `_`. Thanks for your guidance.
